services:
  micam-rs:
    image: micam-rs:local
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: false
    network_mode: host
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - ./config:/config
    restart: always

  miot-oauth:
    image: micam-rs:local
    build:
      context: .
      dockerfile: Dockerfile
    command: miloco_oauth_redirect
    env_file:
      - path: .env
        required: false
    network_mode: host
    volumes:
      - ./config:/config
    profiles: ["oauth"]
    restart: "no"
